// High-quality food images from Unsplash that match Factor75's aesthetic
export const mealImages = {
  // Protein-rich meals
  grilledChicken:
    'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&h=600&fit=crop&crop=center',
  salmonDish:
    'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&h=600&fit=crop&crop=center',
  beefSteak:
    'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=600&fit=crop&crop=center',

  // Gourmet presentations
  platedMeal1:
    'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=600&fit=crop&crop=center',
  platedMeal2:
    'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=600&fit=crop&crop=center',
  platedMeal3:
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=600&h=600&fit=crop&crop=center',

  // Healthy vegetables and sides
  roastedVeggies:
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=600&fit=crop&crop=center',
  freshSalad:
    'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop&crop=center',

  // Chef and kitchen
  chef: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&crop=center',
  kitchen:
    'https://images.unsplash.com/photo-1556909235-f574e32415fb?w=800&h=600&fit=crop&crop=center',

  // Meal preparation
  mealPrep1:
    'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=600&h=600&fit=crop&crop=center',
  mealPrep2:
    'https://images.unsplash.com/photo-1615937691194-b4fb8999d4c5?w=600&h=600&fit=crop&crop=center',

  // Specific meal types matching Factor75's menu
  pastaDishe:
    'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&h=600&fit=crop&crop=center',
  seafoodPlate:
    'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=600&h=600&fit=crop&crop=center',
  porkTenderloin:
    'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&h=600&fit=crop&crop=center',

  // Bowl meals
  proteinBowl:
    'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600&h=600&fit=crop&crop=center',
  chickenBowl:
    'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=600&fit=crop&crop=center',
}

export const heroImages = {
  // Main hero background options
  mealSpread:
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&h=800&fit=crop&crop=center',
  kitchenScene:
    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop&crop=center',
  freshIngredients:
    'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1200&h=800&fit=crop&crop=center',
}

// 40 Unique Professional Factor75-Style Menu Items (No Duplicates, Organized by Category)
export const sampleMeals = [
  // CHICKEN ENTREES (12 items) - High-quality poultry dishes
  {
    id: 'chicken-001',
    name: 'Horseradish Crusted Chicken',
    description:
      'with Creamy Parmesan Brussels Sprouts, Cabbage & Chili-Butter Broccoli',
    short_description: 'Protein-packed chicken with gourmet vegetables',
    calories: 620,
    protein: 45,
    price: 11.0,
    image_url: mealImages.grilledChicken,
    is_popular: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-002',
    name: 'Jalapeño-Lime Cheddar Chicken',
    description: 'with Spicy Cilantro Cauli Rice',
    short_description: 'Zesty chicken with bold southwestern flavors',
    calories: 590,
    protein: 43,
    price: 12.0,
    image_url: mealImages.chickenBowl,
    is_popular: true,
    dietary_tags: 'High Protein, Keto',
    category: 'chicken',
  },
  {
    id: 'chicken-003',
    name: 'Thai-Style Green Chicken Curry',
    description: 'with Green Beans, Coconut-Lime Rice & Peppers',
    short_description: 'Aromatic Thai curry with tender chicken',
    calories: 580,
    protein: 40,
    price: 12.5,
    image_url: mealImages.chickenBowl,
    is_popular: false,
    is_new: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-004',
    name: 'Mediterranean Chicken & Olives',
    description: 'with Herbed Quinoa, Roasted Tomatoes & Feta',
    short_description: 'Fresh Mediterranean flavors',
    calories: 540,
    protein: 38,
    price: 11.5,
    image_url: mealImages.platedMeal1,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-005',
    name: 'BBQ Chicken Breast & Sweet Potatoes',
    description: 'with Cheddar Cheese & Roasted Broccoli',
    short_description: 'Classic BBQ comfort food',
    calories: 560,
    protein: 41,
    price: 11.0,
    image_url: mealImages.grilledChicken,
    is_popular: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-006',
    name: 'Cajun Blackened Chicken',
    description: 'with Dirty Rice & Okra Succotash',
    short_description: 'Bold Cajun spices and Southern sides',
    calories: 600,
    protein: 44,
    price: 12.5,
    image_url: mealImages.platedMeal2,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-007',
    name: 'Lemon Herb Chicken Piccata',
    description: 'with Garlic Mashed Cauliflower & Asparagus',
    short_description: 'Classic Italian preparation',
    calories: 530,
    protein: 36,
    price: 11.5,
    image_url: mealImages.grilledChicken,
    is_popular: false,
    dietary_tags: 'High Protein, Keto',
    category: 'chicken',
  },
  {
    id: 'chicken-008',
    name: 'Buffalo Chicken Bowl',
    description: 'with Blue Cheese Cauliflower Rice & Celery Slaw',
    short_description: 'Game day flavors in a healthy bowl',
    calories: 580,
    protein: 42,
    price: 12.0,
    image_url: mealImages.chickenBowl,
    is_popular: true,
    dietary_tags: 'High Protein, Keto',
    category: 'chicken',
  },
  {
    id: 'chicken-009',
    name: 'Moroccan Spiced Chicken',
    description: 'with Apricot Couscous & Harissa Vegetables',
    short_description: 'Exotic North African spices',
    calories: 560,
    protein: 38,
    price: 12.5,
    image_url: mealImages.platedMeal3,
    is_popular: false,
    is_new: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-010',
    name: 'Teriyaki Chicken & Pineapple',
    description: 'with Sesame Brown Rice & Stir-Fried Vegetables',
    short_description: 'Sweet and savory Hawaiian-style',
    calories: 590,
    protein: 40,
    price: 12.0,
    image_url: mealImages.chickenBowl,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-011',
    name: 'Truffle Mushroom Chicken Breast',
    description: 'with Herb Roasted Red Potatoes',
    short_description: 'Luxurious truffle flavors',
    calories: 590,
    protein: 42,
    price: 13.0,
    image_url: mealImages.grilledChicken,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },
  {
    id: 'chicken-012',
    name: 'Chicken Marsala',
    description: 'with Creamy Mushroom Sauce & Garlic Green Beans',
    short_description: 'Rich Italian wine sauce',
    calories: 580,
    protein: 41,
    price: 13.0,
    image_url: mealImages.grilledChicken,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein',
    category: 'chicken',
  },

  // SEAFOOD ENTREES (10 items) - Premium fish and shellfish
  {
    id: 'seafood-001',
    name: 'Pesto Salmon',
    description: 'with Creamed Spinach & Tomato Butter Haricots Verts',
    short_description: 'Fresh salmon with Mediterranean flavors',
    calories: 580,
    protein: 42,
    price: 13.0,
    image_url: mealImages.salmonDish,
    is_popular: true,
    is_new: true,
    dietary_tags: 'High Protein, Keto',
    category: 'seafood',
  },
  {
    id: 'seafood-002',
    name: 'Korean-Style Salmon & Gochujang Sauce',
    description: 'with Rice, Sesame Cabbage, Bok Choy & Carrots',
    short_description: 'Bold Asian-inspired flavors',
    calories: 600,
    protein: 44,
    price: 14.0,
    image_url: mealImages.seafoodPlate,
    is_popular: false,
    is_new: true,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-003',
    name: 'Ginger Teriyaki Salmon',
    description: 'with Forbidden Rice & Sesame Green Beans',
    short_description: 'Japanese-inspired glazed salmon',
    calories: 620,
    protein: 46,
    price: 14.5,
    image_url: mealImages.salmonDish,
    is_popular: true,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-004',
    name: 'Lemon Dill Cod',
    description: 'with Herb Quinoa Pilaf & Roasted Asparagus',
    short_description: 'Light and flaky white fish',
    calories: 480,
    protein: 35,
    price: 13.5,
    image_url: mealImages.seafoodPlate,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-005',
    name: 'Blackened Mahi-Mahi',
    description: 'with Coconut Rice & Mango Salsa',
    short_description: 'Tropical island flavors',
    calories: 550,
    protein: 40,
    price: 14.0,
    image_url: mealImages.seafoodPlate,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-006',
    name: 'Tex-Mex Shrimp Bowl',
    description: 'with Pico de Gallo, Queso Fresco & Zucchini',
    short_description: 'Southwestern shrimp bowl',
    calories: 520,
    protein: 36,
    price: 13.0,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    dietary_tags: 'High Protein, Keto',
    category: 'seafood',
  },
  {
    id: 'seafood-007',
    name: 'Creole Shrimp & Smoky Cheddar Grits',
    description: 'with Garlicky Green Beans & Peppers',
    short_description: 'Southern comfort with a kick',
    calories: 580,
    protein: 37,
    price: 13.5,
    image_url: mealImages.seafoodPlate,
    is_popular: false,
    is_new: true,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-008',
    name: 'Mediterranean Sea Bass',
    description: 'with Olive Tapenade, Quinoa & Roasted Peppers',
    short_description: 'Elegant Mediterranean preparation',
    calories: 540,
    protein: 41,
    price: 15.0,
    image_url: mealImages.seafoodPlate,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-009',
    name: 'Coconut Curry Shrimp',
    description: 'with Jasmine Rice & Asian Vegetables',
    short_description: 'Rich coconut curry with tender shrimp',
    calories: 570,
    protein: 35,
    price: 13.5,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'seafood',
  },
  {
    id: 'seafood-010',
    name: 'Pan-Seared Scallops',
    description: 'with Cauliflower Puree & Pancetta Crisps',
    short_description: 'Restaurant-quality scallops',
    calories: 490,
    protein: 32,
    price: 16.0,
    image_url: mealImages.seafoodPlate,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein, Keto',
    category: 'seafood',
  },

  // BEEF & PORK ENTREES (10 items) - Premium red meat and pork
  {
    id: 'beef-001',
    name: 'Garlic Herb Ribeye Steak',
    description: 'with Truffle Mashed Potatoes & Grilled Asparagus',
    short_description: 'Premium cut with luxury sides',
    calories: 680,
    protein: 48,
    price: 16.0,
    image_url: mealImages.beefSteak,
    is_popular: true,
    dietary_tags: 'High Protein',
    category: 'beef',
  },
  {
    id: 'beef-002',
    name: 'Chimichurri Pork Tenderloin',
    description: 'with Pepper Cauli Mash & Squash Medley',
    short_description: 'Tender pork with vibrant chimichurri sauce',
    calories: 540,
    protein: 38,
    price: 12.0,
    image_url: mealImages.porkTenderloin,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'Carb Conscious',
    category: 'pork',
  },
  {
    id: 'beef-003',
    name: 'Korean BBQ Beef Bowl',
    description: 'with Kimchi Rice & Sesame Vegetables',
    short_description: 'Bold Korean flavors',
    calories: 620,
    protein: 43,
    price: 13.5,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    is_new: true,
    dietary_tags: 'High Protein',
    category: 'beef',
  },
  {
    id: 'pork-001',
    name: 'Balsamic Glazed Pork Medallions',
    description: 'with Roasted Butternut Squash & Green Beans',
    short_description: 'Sweet and tangy glazed pork',
    calories: 560,
    protein: 39,
    price: 12.5,
    image_url: mealImages.porkTenderloin,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'pork',
  },
  {
    id: 'beef-004',
    name: 'Beef Bourguignon',
    description: 'with Herb Mashed Potatoes & Pearl Onions',
    short_description: 'Classic French braised beef',
    calories: 640,
    protein: 44,
    price: 15.0,
    image_url: mealImages.beefSteak,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein',
    category: 'beef',
  },
  {
    id: 'pork-002',
    name: 'Cuban Mojo Pork',
    description: 'with Black Beans, Rice & Plantains',
    short_description: 'Traditional Cuban flavors',
    calories: 590,
    protein: 40,
    price: 12.0,
    image_url: mealImages.porkTenderloin,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'pork',
  },
  {
    id: 'beef-005',
    name: 'Mongolian Beef',
    description: 'with Scallion Rice & Stir-Fried Vegetables',
    short_description: 'Sweet and savory Asian beef',
    calories: 610,
    protein: 42,
    price: 13.5,
    image_url: mealImages.beefSteak,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'beef',
  },
  {
    id: 'lamb-001',
    name: 'Herb-Crusted Lamb Chops',
    description: 'with Mint Chimichurri & Roasted Vegetables',
    short_description: 'Elegant Mediterranean lamb',
    calories: 580,
    protein: 41,
    price: 16.5,
    image_url: mealImages.beefSteak,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'High Protein, Keto',
    category: 'lamb',
  },
  {
    id: 'beef-006',
    name: 'Texas-Style Brisket',
    description: 'with Smoky Baked Beans & Coleslaw',
    short_description: 'Authentic BBQ brisket',
    calories: 650,
    protein: 45,
    price: 14.0,
    image_url: mealImages.beefSteak,
    is_popular: true,
    dietary_tags: 'High Protein',
    category: 'beef',
  },
  {
    id: 'pork-003',
    name: 'Apple Bourbon Glazed Pork Chops',
    description: 'with Sweet Potato Mash & Sautéed Spinach',
    short_description: 'Sweet and smoky pork perfection',
    calories: 570,
    protein: 38,
    price: 12.5,
    image_url: mealImages.porkTenderloin,
    is_popular: false,
    dietary_tags: 'High Protein',
    category: 'pork',
  },

  // PASTA & COMFORT FOODS (4 items) - Hearty comfort dishes
  {
    id: 'pasta-001',
    name: 'Truffle Mac & Cheese',
    description: 'with Gruyere, White Cheddar & Herb Breadcrumbs',
    short_description: 'Luxury comfort food',
    calories: 580,
    protein: 26,
    price: 13.0,
    image_url: mealImages.pastaDishe,
    is_popular: true,
    dietary_tags: 'Comfort Food',
    category: 'pasta',
  },
  {
    id: 'pasta-002',
    name: 'Beef Bolognese Penne',
    description: 'with Fresh Basil & Parmesan',
    short_description: 'Classic Italian pasta',
    calories: 590,
    protein: 32,
    price: 12.5,
    image_url: mealImages.pastaDishe,
    is_popular: true,
    dietary_tags: 'High Protein',
    category: 'pasta',
  },
  {
    id: 'pasta-003',
    name: 'Lobster Ravioli',
    description: 'with Lemon Butter Sauce & Asparagus',
    short_description: 'Premium seafood pasta',
    calories: 540,
    protein: 28,
    price: 15.5,
    image_url: mealImages.pastaDishe,
    is_popular: false,
    is_top_rated: true,
    dietary_tags: 'Premium',
    category: 'pasta',
  },
  {
    id: 'comfort-001',
    name: 'Wild Mushroom Risotto',
    description: 'with Truffle Oil, Parmesan & Arugula',
    short_description: 'Earthy Italian rice dish',
    calories: 480,
    protein: 16,
    price: 12.0,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    dietary_tags: 'Vegetarian',
    category: 'comfort',
  },

  // PLANT-BASED & ALTERNATIVE PROTEINS (4 items) - Vegetarian and vegan options
  {
    id: 'plant-001',
    name: 'Caribbean Spiced Tofu',
    description: 'with Beans, Rice, Mango Salsa & Coconut Jerk Sauce',
    short_description: 'Tropical plant-based protein',
    calories: 460,
    protein: 22,
    price: 10.5,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    is_new: true,
    dietary_tags: 'Vegan, Plant-Based',
    category: 'plant-based',
  },
  {
    id: 'plant-002',
    name: 'Japanese Tofu & Sesame Brown Rice',
    description: 'with Bok Choy, Mushrooms & Peanut Sauce',
    short_description: 'Asian-inspired plant protein',
    calories: 440,
    protein: 20,
    price: 10.0,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    dietary_tags: 'Vegan, Plant-Based',
    category: 'plant-based',
  },
  {
    id: 'plant-003',
    name: 'Quinoa-Stuffed Bell Peppers',
    description: 'with Black Beans, Corn & Cilantro Lime Sauce',
    short_description: 'Colorful vegetarian option',
    calories: 420,
    protein: 18,
    price: 10.0,
    image_url: mealImages.roastedVeggies,
    is_popular: false,
    dietary_tags: 'Vegetarian, Fiber-Filled',
    category: 'vegetarian',
  },
  {
    id: 'plant-004',
    name: 'Mediterranean Chickpea Bowl',
    description: 'with Hummus, Tzatziki, Olives & Roasted Vegetables',
    short_description: 'Protein-rich Mediterranean bowl',
    calories: 480,
    protein: 20,
    price: 10.5,
    image_url: mealImages.proteinBowl,
    is_popular: false,
    dietary_tags: 'Vegetarian, High Fiber',
    category: 'vegetarian',
  },
]
